package sbnz.integracija.rules;
import better.me.enums.*;
import better.me.model.*;

rule "Classify User By Age ELDER"
	agenda-group "age"
	when
	    $user: RegisteredUser( age >= 60 && age < 2147483647 ) @Watch(!ageCategory)
	then
	    modify($user){ setAgeCategory("ELDER"); }
	end

rule "Classify User By Age ADULT"
	agenda-group "age"
	when
	    $user: RegisteredUser( age >= 46 && age < 60 ) @Watch(!ageCategory)
	then
	    modify($user){ setAgeCategory("ADULT"); }
	end

rule "Classify User By Age YOUNG_ADULT"
	agenda-group "age"
	when
	    $user: RegisteredUser( age >= 20 && age < 46 ) @Watch(!ageCategory)
	then
	    modify($user){ setAgeCategory("YOUNG_ADULT"); }
	end

rule "Classify User By Age TEEN"
	agenda-group "age"
	when
	    $user: RegisteredUser( age >= 13 && age < 20 ) @Watch(!ageCategory)
	then
	    modify($user){ setAgeCategory("TEEN"); }
	end

rule "Classify User By Age CHILD"
	agenda-group "age"
	when
	    $user: RegisteredUser( age >= 0 && age < 13 ) @Watch(!ageCategory)
	then
	    modify($user){ setAgeCategory("CHILD"); }
	end


