package sbnz.integracija.rules

import better.me.enums.*;
import better.me.model.*;
import better.me.dto.*;
import better.me.util.*;

global MyLogger myLogger;


rule "BMI determination"
	agenda-group "bmi"
	salience 100
    when
        $user: RegisteredUser(bmi == 0, $weight: weight, $height: height)
    then
        myLogger.log("BMI determined");
        modify ($user) {setBmi($weight/(($height/100)*($height/100)));}
end

rule "Male, age 14-16, bmi < 16.5 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 14, age < 16, bmi < 16.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 14-16, bmi < 16.5 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Male, age 14-16, bmi >= 26.5 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 14, age < 16, bmi >= 26.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 14-16, bmi >= 26.5 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Male, age 14-16, bmi >= 16.5, bmi < 26.5 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 14, age < 16, bmi >= 16.5, bmi < 26.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 14-16, bmi >= 16.5, bmi < 26.5 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Female, age 14-16, bmi < 16 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 14, age < 16, bmi < 16)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 14-16, bmi < 16 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Female, age 14-16, bmi >= 28 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 14, age < 16, bmi >= 28)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 14-16, bmi >= 28 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Female, age 14-16, bmi >= 16, bmi < 28 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 14, age < 16, bmi >= 16, bmi < 28)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 14-16, bmi >= 16, bmi < 28 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Male, age 16-18, bmi < 17.5 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 16, age < 18, bmi < 17.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 16-18, bmi < 17.5 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Male, age 16-18, bmi >= 28 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 16, age < 18, bmi >= 28)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 16-18, bmi >= 28 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Male, age 16-18, bmi >= 17.5, bmi < 28 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 16, age < 18, bmi >= 17.5, bmi < 28)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 16-18, bmi >= 17.5, bmi < 28 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Female, age 16-18, bmi < 17 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 16, age < 18, bmi < 17)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 16-18, bmi < 17 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Female, age 16-18, bmi >= 29.5 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 16, age < 18, bmi >= 29.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 16-18, bmi >= 29.5 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Female, age 16-18, bmi >= 17, bmi < 29.5 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 16, age < 18, bmi >= 17, bmi < 29.5)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 16-18, bmi >= 17, bmi < 29.5 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Male, age 18-20, bmi < 19 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 18, age < 20, bmi < 19)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 18-20, bmi < 19 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Male, age 18-20, bmi >= 30 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 18, age < 20, bmi >= 30)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 18-20, bmi >= 30 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Male, age 18-20, bmi >= 19, bmi < 30 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.MALE.value, age >= 18, age < 20, bmi >= 19, bmi < 30)
    	$week: Week(goal == null)
    then
        myLogger.log("Male, age 18-20, bmi >= 19, bmi < 30 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Female, age 18-20, bmi < 18 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 18, age < 20, bmi < 18)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 18-20, bmi < 18 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "Female, age 18-20, bmi >= 31 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 18, age < 20, bmi >= 31)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 18-20, bmi >= 31 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "Female, age 18-20, bmi >= 18, bmi < 31 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(sex == Sex.FEMALE.value, age >= 18, age < 20, bmi >= 18, bmi < 31)
    	$week: Week(goal == null)
    then
        myLogger.log("Female, age 18-20, bmi >= 18, bmi < 31 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "age 20+, bmi < 18.5 GAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(age >= 20, bmi < 18.5)
    	$week: Week(goal == null)
    then
        myLogger.log("age 20+, bmi < 18.5 GAIN_WEIGHT");
        modify ($week) {setGoal("GAIN_WEIGHT");}
end

rule "age 20+, bmi >= 25 LOSE_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(age >= 20, bmi >= 25)
    	$week: Week(goal == null)
    then
        myLogger.log("age 20+, bmi >= 25 LOSE_WEIGHT");
        modify ($week) {setGoal("LOSE_WEIGHT");}
end

rule "age 20+, bmi >= 18.5, bmi < 15 MAINTAIN_WEIGHT"
	agenda-group "bmi"
    when
    	$user: RegisteredUser(age >= 20, bmi >= 18.5, bmi < 25)
    	$week: Week(goal == null)
    then
        myLogger.log("age 20+, bmi >= 18.5, bmi < 25 MAINTAIN_WEIGHT");
        modify ($week) {setGoal("MAINTAIN_WEIGHT");}
end

rule "Change agenda-group to nutrition"
	agenda-group "bmi"
	salience -Integer.MAX_VALUE
	when
		Week()
	then
		myLogger.log("Changed agenda-group from bmi to nutrition");
		kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("nutrition").setFocus();
end