package sbnz.integracija.rules;

import better.me.enums.*;
import better.me.model.*;
import better.me.dto.*;
import better.me.facts.*;
import better.me.util.*;
import java.util.Map;

global MyLogger myLogger;


rule "Determine body type"
	agenda-group "body-type"
    when
    	$a: Answers($answers: answers)
        $u: UserAnswers($userAnswers: userAnswers)
        Number($value: intValue >= 7) from accumulate (
        	Map.Entry($t:this, $answers.entrySet() contains this) from $userAnswers.entrySet(),
        	count($t)
        )
        $bodyType: BodyTypeFact(bodyType == null)
    then
        myLogger.log("User has endomorph body type");
        modify ($bodyType) {setBodyType($a.getBodyType());}
end