package sbnz.integracija.rules;
import better.me.enums.*;
import better.me.model.*;
import better.me.dto.*;
import better.me.modelDB.*;
import better.me.util.*;

rule "Rule PRO Rule"
    agenda-group "category"
    when 
		$user : RegisteredUser($score: score, $previousCategory : previousCategory, $score >= 1050, $score < 2147483647, $category: category) @Watch(!category, !previousCategory)
	then
		if (!($category.equals("PRO"))) {
			modify($user){ setPreviousCategory($category); }
		}
		modify($user){ setCategory("PRO"); }
	end

rule "Rule ADVANCED Rule"
    agenda-group "category"
    when 
		$user : RegisteredUser($score: score, $previousCategory : previousCategory, $score >= 500, $score < 1050, $category: category) @Watch(!category, !previousCategory)
	then
		if (!($category.equals("ADVANCED"))) {
			modify($user){ setPreviousCategory($category); }
		}
		modify($user){ setCategory("ADVANCED"); }
	end

rule "Rule INTERMEDIATE Rule"
    agenda-group "category"
    when 
		$user : RegisteredUser($score: score, $previousCategory : previousCategory, $score >= 200, $score < 500, $category: category) @Watch(!category, !previousCategory)
	then
		if (!($category.equals("INTERMEDIATE"))) {
			modify($user){ setPreviousCategory($category); }
		}
		modify($user){ setCategory("INTERMEDIATE"); }
	end

rule "Rule BEGINNER Rule"
    agenda-group "category"
    when 
		$user : RegisteredUser($score: score, $previousCategory : previousCategory, $score >= 0, $score < 200, $category: category) @Watch(!category, !previousCategory)
	then
		if (!($category.equals("BEGINNER"))) {
			modify($user){ setPreviousCategory($category); }
		}
		modify($user){ setCategory("BEGINNER"); }
	end


