package sbnz.integracija.rules

import better.me.enums.*;
import better.me.model.*;
import better.me.modelDB.*;
import better.me.dto.*;
import better.me.util.*;

query checkIfWholeWeekIsSubmitted(Week $week)
	 $num := Number(intValue == 7) from accumulate(
		Day($t:this, submitted == true) from $week.getDays(),
		count($t)
 	 )
end

query "Get number of days submitted"(Week $week)
	 $num := Number(intValue >= 0) from accumulate(
		Day($t:this, submitted == true) from $week.getDays(),
		count($t)
 	 )
end