package sbnz.integracija.rules

import better.me.enums.*;
import better.me.model.*;
import better.me.modelDB.*;
import better.me.dto.*;
import better.me.util.*;
import java.util.ArrayList;
import java.util.List;

query mealContainsAllergens(Meal $meal, List $allergens)
	 $num := Number(intValue > 0) from accumulate(
		$ingredient: Ingredient($grocery: grocery, $t: this) from $meal.getIngredients()
		and Allergen(name.equals($grocery.getName())) from $allergens,
		count($t)
 	 )
end

query "Get number of days submitted"(Week $week)
	 $num := Number(intValue >= 0) from accumulate(
		Day($t:this, submitted == true) from $week.getDays(),
		count($t)
 	 )
end