package sbnz.integracija.rules;

import better.me.enums.*;
import better.me.model.*;

global MyLogger myLogger;

rule "Rate meal"
	agenda-group "rate-meal"
	when
	    $newGrade: Grade($newValue: value, $mealId: meal.getId());
	    $meal: Meal(id == $mealId, $grades: grades);
	    Number($gradesSum : intValue) from accumulate (
			$grade: Grade($value: value) from $grades,
			sum($value)
		)
	then
		myLogger.log("Meal rated with rate: " + $newValue + ", grade sum is: " + $gradesSum + ", average rate is now: " + ((double) $gradesSum)/($meal.getGrades().size()) + ", rate count is: " + $meal.getGrades().size());
	    modify($meal){ setAverageGrade(((double) $gradesSum)/$meal.getGrades().size()); }
end